export const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    REFRESH: "/api/v1/auth/refresh",
    LOGOUT: "/api/v1/auth/logout",
    FORGOT_PASSWORD: "/api/v1/auth/forgot-password",
    RESET_PASSWORD: "/api/v1/auth/reset-password",
    ME: "/api/v1/auth/me",
  },
  EMPLOYEES: {
    BASE: "/api/v1/employees",
    DETAIL: (id: string) => `/api/v1/employees/${id}`,
    SEARCH: "/api/v1/employees/search",
  },
  COMPANIES: {
    BASE: "/api/v1/companies",
    DETAIL: (id: string) => `/api/v1/companies/${id}`,
  },
  DEPARTMENTS: {
    BASE: "/api/v1/departments",
    DETAIL: (id: string) => `/api/v1/departments/${id}`,
  },
  DESIGNATIONS: {
    BASE: "/api/v1/designations",
    DETAIL: (id: string) => `/api/v1/designations/${id}`,
  },
  ATTENDANCE: {
    BASE: "/api/v1/attendance",
    CHECK_IN: "/api/v1/attendance/check-in",
    CHECK_OUT: "/api/v1/attendance/check-out",
    MY: "/api/v1/attendance/my",
    SUMMARY: "/api/v1/attendance/summary",
  },
  SHIFTS: {
    BASE: "/api/v1/shifts",
    DETAIL: (id: string) => `/api/v1/shifts/${id}`,
  },
  LEAVES: {
    TYPES: "/api/v1/leave-types",
    APPLICATIONS: "/api/v1/leave-applications",
    APPLICATION_DETAIL: (id: string) => `/api/v1/leave-applications/${id}`,
    BALANCE: "/api/v1/leave-applications/balance",
    POLICIES: "/api/v1/leave-policies",
    HOLIDAYS: "/api/v1/holidays",
  },
  PAYROLL: {
    SALARY_COMPONENTS: "/api/v1/salary-components",
    SALARY_STRUCTURES: "/api/v1/salary-structures",
    SALARY_STRUCTURE_DETAIL: (id: string) => `/api/v1/salary-structures/${id}`,
    PAYROLL_RUNS: "/api/v1/payroll-runs",
    PAYROLL_RUN_DETAIL: (id: string) => `/api/v1/payroll-runs/${id}`,
    PAYSLIPS: "/api/v1/payslips",
    MY_PAYSLIPS: "/api/v1/payslips/my",
    TAX_DECLARATIONS: "/api/v1/tax-declarations",
  },
  RECRUITMENT: {
    JOB_OPENINGS: "/api/v1/job-openings",
    JOB_OPENING_DETAIL: (id: string) => `/api/v1/job-openings/${id}`,
    APPLICATIONS: "/api/v1/applications",
    APPLICATION_DETAIL: (id: string) => `/api/v1/applications/${id}`,
    CANDIDATES: "/api/v1/candidates",
    CANDIDATE_DETAIL: (id: string) => `/api/v1/candidates/${id}`,
    INTERVIEWS: "/api/v1/interviews",
    INTERVIEW_DETAIL: (id: string) => `/api/v1/interviews/${id}`,
    OFFERS: "/api/v1/offer-letters",
    OFFER_DETAIL: (id: string) => `/api/v1/offer-letters/${id}`,
    JD_GENERATE: "/api/v1/jd/generate",
    JD_LIBRARY: "/api/v1/jd/library",
  },
  PERFORMANCE: {
    OKR_CYCLES: "/api/v1/okr/cycles",
    OBJECTIVES: "/api/v1/okr/objectives",
    OBJECTIVE_DETAIL: (id: string) => `/api/v1/okr/objectives/${id}`,
    KEY_RESULTS: "/api/v1/okr/key-results",
    KEY_RESULT_DETAIL: (id: string) => `/api/v1/okr/key-results/${id}`,
    REVIEW_CYCLES: "/api/v1/pms/review-cycles",
    REVIEWS: "/api/v1/pms/reviews",
    REVIEW_DETAIL: (id: string) => `/api/v1/pms/reviews/${id}`,
  },
  TASKS: {
    BASE: "/api/v1/tasks",
    DETAIL: (id: string) => `/api/v1/tasks/${id}`,
    BOARDS: "/api/v1/task-boards",
  },
  FILES: {
    UPLOAD: "/api/v1/files/upload",
    DOWNLOAD: (id: string) => `/api/v1/files/${id}/download`,
  },
  NOTIFICATIONS: {
    BASE: "/api/v1/notifications",
    MARK_READ: (id: string) => `/api/v1/notifications/${id}/read`,
  },
  DASHBOARD: {
    STATS: "/api/v1/dashboard/stats",
    RECENT_HIRES: "/api/v1/dashboard/recent-hires",
    BIRTHDAYS: "/api/v1/dashboard/birthdays",
    PENDING_APPROVALS: "/api/v1/dashboard/pending-approvals",
  },
  SETTINGS: {
    BASE: "/api/v1/settings",
    COMPANY: "/api/v1/settings/company",
  },
} as const;

export const QUERY_KEYS = {
  AUTH: {
    ME: ["auth", "me"],
  },
  EMPLOYEES: {
    ALL: ["employees"],
    LIST: (params?: Record<string, unknown>) => ["employees", "list", params],
    DETAIL: (id: string) => ["employees", "detail", id],
    SEARCH: (query: string) => ["employees", "search", query],
  },
  COMPANIES: {
    ALL: ["companies"],
    LIST: () => ["companies", "list"],
    DETAIL: (id: string) => ["companies", "detail", id],
  },
  DEPARTMENTS: {
    ALL: ["departments"],
    LIST: () => ["departments", "list"],
    DETAIL: (id: string) => ["departments", "detail", id],
  },
  DESIGNATIONS: {
    ALL: ["designations"],
    LIST: () => ["designations", "list"],
  },
  ATTENDANCE: {
    ALL: ["attendance"],
    MY: (params?: Record<string, unknown>) => ["attendance", "my", params],
    LIST: (params?: Record<string, unknown>) => ["attendance", "list", params],
    SUMMARY: (params?: Record<string, unknown>) => ["attendance", "summary", params],
  },
  SHIFTS: {
    ALL: ["shifts"],
    LIST: () => ["shifts", "list"],
  },
  LEAVES: {
    ALL: ["leaves"],
    TYPES: () => ["leaves", "types"],
    APPLICATIONS: (params?: Record<string, unknown>) => ["leaves", "applications", params],
    BALANCE: () => ["leaves", "balance"],
    POLICIES: () => ["leaves", "policies"],
    HOLIDAYS: () => ["leaves", "holidays"],
  },
  PAYROLL: {
    ALL: ["payroll"],
    STRUCTURES: () => ["payroll", "structures"],
    STRUCTURE_DETAIL: (id: string) => ["payroll", "structures", id],
    RUNS: (params?: Record<string, unknown>) => ["payroll", "runs", params],
    RUN_DETAIL: (id: string) => ["payroll", "runs", id],
    PAYSLIPS: (params?: Record<string, unknown>) => ["payroll", "payslips", params],
    MY_PAYSLIPS: () => ["payroll", "my-payslips"],
    TAX_DECLARATIONS: () => ["payroll", "tax-declarations"],
  },
  RECRUITMENT: {
    ALL: ["recruitment"],
    JOB_OPENINGS: (params?: Record<string, unknown>) => ["recruitment", "job-openings", params],
    JOB_OPENING_DETAIL: (id: string) => ["recruitment", "job-openings", id],
    APPLICATIONS: (params?: Record<string, unknown>) => ["recruitment", "applications", params],
    APPLICATION_DETAIL: (id: string) => ["recruitment", "applications", id],
    CANDIDATES: (params?: Record<string, unknown>) => ["recruitment", "candidates", params],
    INTERVIEWS: (params?: Record<string, unknown>) => ["recruitment", "interviews", params],
    OFFERS: (params?: Record<string, unknown>) => ["recruitment", "offers", params],
  },
  PERFORMANCE: {
    ALL: ["performance"],
    OKR_CYCLES: () => ["performance", "okr-cycles"],
    OBJECTIVES: (params?: Record<string, unknown>) => ["performance", "objectives", params],
    OBJECTIVE_DETAIL: (id: string) => ["performance", "objectives", id],
    KEY_RESULTS: (objectiveId: string) => ["performance", "key-results", objectiveId],
    REVIEW_CYCLES: () => ["performance", "review-cycles"],
    REVIEWS: (params?: Record<string, unknown>) => ["performance", "reviews", params],
    REVIEW_DETAIL: (id: string) => ["performance", "reviews", id],
  },
  TASKS: {
    ALL: ["tasks"],
    LIST: (params?: Record<string, unknown>) => ["tasks", "list", params],
    DETAIL: (id: string) => ["tasks", "detail", id],
    BOARDS: () => ["tasks", "boards"],
  },
  DASHBOARD: {
    STATS: ["dashboard", "stats"],
    RECENT_HIRES: ["dashboard", "recent-hires"],
    BIRTHDAYS: ["dashboard", "birthdays"],
    PENDING_APPROVALS: ["dashboard", "pending-approvals"],
  },
  NOTIFICATIONS: {
    ALL: ["notifications"],
    LIST: () => ["notifications", "list"],
  },
} as const;

export const APP_ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/",
  EMPLOYEES: {
    LIST: "/employees",
    CREATE: "/employees/new",
    DETAIL: (id: string) => `/employees/${id}`,
    ORG_CHART: "/employees/org-chart",
  },
  ATTENDANCE: {
    MY: "/attendance",
    ALL: "/attendance/all",
    SHIFTS: "/attendance/shifts",
  },
  LEAVES: {
    DASHBOARD: "/leaves",
    LIST: "/leaves/all",
    APPLY: "/leaves/apply",
    POLICIES: "/leaves/policies",
  },
  PAYROLL: {
    DASHBOARD: "/payroll",
    STRUCTURES: "/payroll/structures",
    RUN: "/payroll/run",
    PAYSLIPS: "/payroll/payslips",
    TAX: "/payroll/tax",
  },
  RECRUITMENT: {
    JOB_OPENINGS: "/recruitment/jobs",
    JOB_OPENING_DETAIL: (id: string) => `/recruitment/jobs/${id}`,
    APPLICATIONS: "/recruitment/applications",
    CANDIDATE_DETAIL: (id: string) => `/recruitment/candidates/${id}`,
    INTERVIEWS: "/recruitment/interviews",
    OFFERS: "/recruitment/offers",
    JD_CREATOR: "/recruitment/jd-creator",
  },
  PERFORMANCE: {
    OKRS: "/performance/okrs",
    OKR_DETAIL: (id: string) => `/performance/okrs/${id}`,
    REVIEWS: "/performance/reviews",
    MY_REVIEW: "/performance/my-review",
    DASHBOARD: "/performance/dashboard",
  },
  TASKS: {
    BOARD: "/tasks",
    LIST: "/tasks/list",
  },
  SETTINGS: {
    COMPANY: "/settings/company",
    PROFILE: "/settings/profile",
  },
} as const;
